import { useEffect } from "react";
import { Howl, Howler } from "howler";
import { useUniverseStore } from "../store/universeStore.js";

/**
 * Cinematic audio engine.
 *
 * Assets live at /public/audio/*.wav (generated by `npm run audio:build`).
 * Every SFX is fully synthesised — no third-party samples, no licensing
 * concerns. WAV plays natively in every modern browser.
 *
 * Behaviour
 * ---------
 *   • A looping ambient bed (shuttle-interior drone) plays constantly
 *     while `audioMuted` is false.
 *   • Any interactive SFX (click / door / warp / ping / boot / black-hole)
 *     automatically "ducks" the ambient — fades it to ~20% for the
 *     duration of the SFX plus a short tail, then smoothly fades it back
 *     up. Overlapping SFX extend the duck.
 *   • Web Audio is unlocked on the user's first pointerdown / keydown,
 *     per browser autoplay policy. Until then nothing plays — even with
 *     `audioMuted = false`.
 *
 * Usage
 * -----
 *   The hook is mounted once at the root (UniverseShell) and owns the
 *   ambient lifecycle. SFX are triggered via the module-level `playFx()`
 *   (or the named helpers), importable from anywhere — no prop drilling.
 */

const BASE_AMBIENT_VOL = 0.26;
const DUCK_VOL = 0.05;
const DUCK_FADE_IN_MS = 70;
const DUCK_FADE_OUT_MS = 450;
/** How long after the SFX finishes before ambient ramps back up. */
const DUCK_TAIL_MS = 100;

/**
 * @typedef {{
 *   src: string,
 *   volume: number,
 *   durationMs: number,
 *   html5?: boolean,
 * }} SfxConfig
 */

/** @type {Record<string, SfxConfig>} */
const SFX_CATALOG = {
  warp:      { src: "/audio/warp.wav",       volume: 0.42, durationMs: 900 },
  ping:      { src: "/audio/ping.wav",       volume: 0.3,  durationMs: 350 },
  click:     { src: "/audio/click.wav",      volume: 0.32, durationMs: 220 },
  doorOpen:  { src: "/audio/door-open.wav",  volume: 0.5,  durationMs: 1400 },
  doorClose: { src: "/audio/door-close.wav", volume: 0.5,  durationMs: 1100 },
  boot:      { src: "/audio/boot.wav",       volume: 0.55, durationMs: 2000 },
  blackHole: { src: "/audio/black-hole.wav", volume: 0.6,  durationMs: 3000 },
};

/**
 * Shared audio state. Held at module scope so the hook and the exported
 * play helpers share a single set of Howl instances.
 */
const state = {
  /** @type {Howl | null} */
  ambient: null,
  ambientFailed: false,
  ambientStarted: false,
  /** @type {Map<string, Howl>} */
  sfx: new Map(),
  /** @type {number | null} */
  unduckTimer: null,
  /** @type {number} epoch ms when the duck should end. */
  duckUntil: 0,
};

/* ------------------------------------------------------------------------ */
/*                                Ducking                                    */
/* ------------------------------------------------------------------------ */

function scheduleUnduck() {
  if (state.unduckTimer != null) {
    clearTimeout(state.unduckTimer);
    state.unduckTimer = null;
  }
  const now = Date.now();
  const wait = Math.max(60, state.duckUntil - now);
  state.unduckTimer = setTimeout(() => {
    state.unduckTimer = null;
    const ambient = state.ambient;
    if (!ambient || useUniverseStore.getState().audioMuted) return;
    try {
      ambient.fade(ambient.volume(), BASE_AMBIENT_VOL, DUCK_FADE_OUT_MS);
    } catch {
      /* ignore */
    }
  }, wait);
}

/**
 * Duck the ambient for `durationMs` + a short tail. Overlapping calls
 * extend the duck — they never cause the ambient to ramp back up mid-SFX.
 */
function duck(durationMs) {
  if (useUniverseStore.getState().audioMuted) return;
  const ambient = state.ambient;
  const end = Date.now() + durationMs + DUCK_TAIL_MS;
  if (end > state.duckUntil) state.duckUntil = end;
  if (ambient && state.ambientStarted) {
    try {
      /** Ramp down (or keep at DUCK_VOL if already ducked). */
      if (ambient.volume() > DUCK_VOL + 0.01) {
        ambient.fade(ambient.volume(), DUCK_VOL, DUCK_FADE_IN_MS);
      }
    } catch {
      /* ignore */
    }
  }
  scheduleUnduck();
}

/* ------------------------------------------------------------------------ */
/*                                SFX                                        */
/* ------------------------------------------------------------------------ */

/**
 * Lazily instantiate (and cache) a Howl for a named SFX.
 * @param {keyof typeof SFX_CATALOG} name
 */
function getSfx(name) {
  const cached = state.sfx.get(name);
  if (cached) return cached;
  const cfg = SFX_CATALOG[name];
  if (!cfg) return null;
  try {
    const howl = new Howl({
      src: [cfg.src],
      format: ["wav"],
      volume: cfg.volume,
      preload: true,
      onloaderror: () => state.sfx.delete(name),
      onplayerror: () => state.sfx.delete(name),
    });
    state.sfx.set(name, howl);
    return howl;
  } catch {
    return null;
  }
}

/**
 * Play a named SFX. Automatically ducks the ambient for the SFX duration.
 * Silent when audio is muted.
 *
 * @param {keyof typeof SFX_CATALOG} name
 */
export function playFx(name) {
  if (useUniverseStore.getState().audioMuted) return;
  const cfg = SFX_CATALOG[name];
  if (!cfg) return;
  const sfx = getSfx(name);
  if (!sfx) return;
  duck(cfg.durationMs);
  try {
    sfx.play();
  } catch {
    /* ignore */
  }
}

export const playWarp = () => playFx("warp");
export const playPing = () => playFx("ping");
export const playClick = () => playFx("click");
export const playDoorOpen = () => playFx("doorOpen");
export const playDoorClose = () => playFx("doorClose");
export const playBoot = () => playFx("boot");
export const playBlackHole = () => playFx("blackHole");

/* ------------------------------------------------------------------------ */
/*                           Ambient lifecycle                               */
/* ------------------------------------------------------------------------ */

function ensureAmbient() {
  if (state.ambient || state.ambientFailed) return state.ambient;
  try {
    state.ambient = new Howl({
      src: ["/audio/ambient.wav"],
      format: ["wav"],
      loop: true,
      volume: BASE_AMBIENT_VOL,
      preload: true,
      onloaderror: () => {
        state.ambientFailed = true;
        state.ambient = null;
      },
    });
  } catch {
    state.ambientFailed = true;
    state.ambient = null;
  }
  return state.ambient;
}

function startAmbient() {
  const h = ensureAmbient();
  if (!h) return;
  if (!h.playing()) {
    const play = () => {
      try {
        h.volume(BASE_AMBIENT_VOL);
        h.play();
        state.ambientStarted = true;
      } catch {
        /* ignore */
      }
    };
    if (h.state() === "unloaded") {
      h.once("load", play);
      h.load();
    } else {
      play();
    }
  }
}

function stopAmbient() {
  state.ambientStarted = false;
  if (state.unduckTimer != null) {
    clearTimeout(state.unduckTimer);
    state.unduckTimer = null;
  }
  state.duckUntil = 0;
  const h = state.ambient;
  if (!h) return;
  try {
    h.stop();
  } catch {
    /* ignore */
  }
}

/* ------------------------------------------------------------------------ */
/*                                 Hook                                      */
/* ------------------------------------------------------------------------ */

/**
 * Mount once at the root. Owns the ambient track's lifecycle and unlocks
 * Web Audio on the first user gesture. Returns the SFX helpers for
 * convenience, but they are also importable directly as module exports.
 */
export function useCinematicAudio() {
  const muted = useUniverseStore((s) => s.audioMuted);

  /** Unlock WebAudio on the first user gesture (required by all browsers). */
  useEffect(() => {
    let unlocked = false;
    const unlock = () => {
      if (unlocked) return;
      unlocked = true;
      try {
        if (Howler.ctx && Howler.ctx.state === "suspended") {
          Howler.ctx.resume();
        }
      } catch {
        /* ignore */
      }
    };
    window.addEventListener("pointerdown", unlock, { passive: true });
    window.addEventListener("keydown", unlock, { passive: true });
    window.addEventListener("touchstart", unlock, { passive: true });
    return () => {
      window.removeEventListener("pointerdown", unlock);
      window.removeEventListener("keydown", unlock);
      window.removeEventListener("touchstart", unlock);
    };
  }, []);

  /** Ambient start/stop follows the mute flag. */
  useEffect(() => {
    if (muted) {
      stopAmbient();
      return;
    }
    startAmbient();
  }, [muted]);

  return {
    playWarp,
    playPing,
    playClick,
    playDoorOpen,
    playDoorClose,
    playBoot,
    playBlackHole,
    playFx,
  };
}
