#!/usr/bin/env node
/**
 * Pulls siteSettings + projects from Sanity → src/generated/content.manifest.js.
 * Without SANITY_PROJECT_ID, re-exports local bundled content.
 *
 * Deploy hook: in Sanity → API → Webhooks, POST your host's rebuild URL on
 * document publish so CI runs `npm run build` (which runs content:pull via prebuild).
 */
import { createClient } from "@sanity/client";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import "dotenv/config";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const manifestPath = join(root, "src", "generated", "content.manifest.js");

const localReexport = `export { projects, siteSettings, contentSource } from "../data/content.local.manifest.js";
`;

const projectQuery = `*[_type == "project" && defined(slug.current)] | order(sortOrder asc, coalesce(year, 0) desc) {
  "name": title,
  "slug": slug.current,
  tagline,
  description,
  body,
  "image": coverImage.asset->url,
  "link": liveUrl,
  repoUrl,
  articleUrl,
  starPosition,
  year,
  roles,
  stack,
  featured,
  sortOrder
}`;

const settingsQuery = `*[_type == "siteSettings"][0]{
  siteTitle,
  tagline,
  statusLine,
  availableForWork,
  defaultMetaDescription,
  resumeUrl,
  cvUrl,
  contactEmail,
  socialLinks,
  bootMessages
}`;

function writeLocalReexport(reason) {
  writeFileSync(manifestPath, localReexport, "utf8");
  console.warn(`[content:pull] ${reason} — using local content from src/data/content.local.manifest.js`);
}

function writeSanityManifest(projects, siteSettings) {
  const settings = siteSettings && typeof siteSettings === "object" ? siteSettings : {};
  const body = `// Auto-generated by scripts/fetch-content.mjs — do not edit by hand
export const projects = ${JSON.stringify(projects, null, 2)};

export const siteSettings = ${JSON.stringify(settings, null, 2)};

export const contentSource = "sanity";
`;
  writeFileSync(manifestPath, body, "utf8");
  console.log(
    `[content:pull] Wrote ${projects.length} project(s) + siteSettings → src/generated/content.manifest.js`,
  );
}

const projectId = process.env.SANITY_PROJECT_ID?.trim();
const dataset = process.env.SANITY_DATASET?.trim() || "production";

if (!projectId) {
  writeLocalReexport("SANITY_PROJECT_ID is not set");
  process.exit(0);
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: "2024-01-01",
  useCdn: true,
});

try {
  const [projects, siteSettings] = await Promise.all([
    client.fetch(projectQuery),
    client.fetch(settingsQuery),
  ]);

  if (!Array.isArray(projects)) {
    writeLocalReexport("Unexpected projects response from Sanity");
    process.exit(0);
  }

  const normalized = projects.map((row) => ({
    name: row.name,
    slug: row.slug,
    tagline: row.tagline ?? "",
    description: row.description ?? "",
    body: Array.isArray(row.body) ? row.body : [],
    image: row.image ?? "",
    link: row.link ?? "",
    repoUrl: row.repoUrl ?? "",
    articleUrl: row.articleUrl ?? "",
    starPosition: row.starPosition ?? undefined,
    year: row.year,
    roles: row.roles,
    stack: row.stack,
    featured: row.featured,
    sortOrder: row.sortOrder,
  }));

  writeSanityManifest(normalized, siteSettings ?? {});
} catch (err) {
  console.error("[content:pull]", err.message || err);
  writeLocalReexport("Sanity fetch failed");
  process.exit(0);
}
